# -*- coding: utf-8 -*-
"""Brain_Cancer_Processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZP3KFZliYiF-zQBwPPtrBI1VE5Qk0HF
"""

# Dataset: difg_glass_clinical_data.csv
# Target:  Overall Survival (months) — regression
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import plotly.express as px

from sklearn.feature_selection import mutual_info_regression, SelectKBest, RFE, RFECV
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer
from sklearn.model_selection import (
    GridSearchCV, KFold, train_test_split, cross_val_score
)
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline

import warnings
warnings.filterwarnings("ignore")

RANDOM_STATE = 42  # Global seed

df = pd.read_csv("difg_glass_clinical_data.csv")
print("Shape:", df.shape)
print(df.head())
print("\nColumns:\n", df.columns.tolist())
print("\nDuplicates:", df.duplicated().sum())
print("\nNull counts:\n", df.isnull().sum())

# Dropping redundant or non-clinically relevant columns
df.drop(columns=[
    "Surgery Indication", "RNA Aliquot Barcode", "Surgery Extent of Resection",
    "Surgery Type", "MGMT Methylation Method", "DNA Aliquot Barcode",
    "Tissue Source", "MGMT Methylation", "Surgery Laterality",
    "Surgery Location", "Cancer Type", "Tumor Classification",
], inplace=True, errors="ignore")

df.pop("Codeletion Status")
df.pop("IDH Status")

df.replace({
    "No": 0, "Yes": 1,
    "IV": 4, "II": 2, "III": 3,
    "1:DECEASED": 1, "0:LIVING": 0,
    "Male": 1, "Female": 0,
}, inplace=True)

# Group rare conditions into broader cancer groups
df.replace({
    "Occipitial lobe":          "Occipital lobe",
    "Temporo-Occipital lobe ":  "Occipital lobe",
    "Parieto-Occipital lobe":   "Occipital lobe",
    "Temporo-Occipital lobe":   "Occipital lobe",
    "Fronto-Temporal lobe":     "Frontal lobe",
    "Fronto-Parietal lobe":     "Frontal lobe",
    "Frontoparietal":           "Frontal lobe",
    "Frontal":                  "Frontal lobe",
}, inplace=True)


df["IDH and Codeletion Status"].fillna(
    df["IDH and Codeletion Status"].mode()[0], inplace=True
)

df.loc[df["Concurrent TMZ Treatment"] == 1, "TMZ Treatment"] = 1
df.loc[df["TMZ Treatment"] == 0, "6 TMZ Treatment Cycles"]   = 0
df.loc[df["TMZ Treatment"] == 0, "TMZ Treatment Cycles"]     = 0.0
df.loc[df["TMZ Treatment"] == 0, "Concurrent TMZ Treatment"] = 0
df.loc[df["Radiotherapy Treatment"] == 0, "Radiation Dose"]  = 0.0

# KNN
NUMERIC_COLS = [
    "Age", "Aklylating Agents Treatment", "ESTIMATE Score",
    "Fraction Genome Altered", "Immune Score", "Mutation Count",
    "Overall Survival (months)", "Overall Survival", "Purity",
    "Sex", "Stromal Score", "Concurrent TMZ Treatment",
    "Radiation Dose", "Radiotherapy Treatment",
    "TMZ Treatment", "TMZ Treatment Cycles", "6 TMZ Treatment Cycles",
    "Tumor Grade",
]

NUMERIC_COLS = [c for c in NUMERIC_COLS if c in df.columns]

imputer = KNNImputer(n_neighbors=2)
df[NUMERIC_COLS] = imputer.fit_transform(df[NUMERIC_COLS])

# Drop Nulls
df.dropna(inplace=True)
print("\nNull counts after imputation:\n", df.isnull().sum())

# One hot Encoding
df_encoded = pd.get_dummies(df, columns=[
    "IDH and Codeletion Status", "Cancer Type Detailed",
    "Sample Type", "Analysis Type", "Histology",
])
print("\nEncoded shape:", df_encoded.shape)

numeric_encoded = df_encoded.select_dtypes(include=np.number).columns

cols_with_outliers = []
for col in numeric_encoded:
    upper = df_encoded[col].mean() + 3 * df_encoded[col].std()
    lower = df_encoded[col].mean() - 3 * df_encoded[col].std()
    if df_encoded[col].max() > upper or df_encoded[col].min() < lower:
        cols_with_outliers.append(col)

print(f"\nColumns with outliers beyond 3σ: {len(cols_with_outliers)}")

for col in cols_with_outliers:
    upper = df_encoded[col].mean() + 3 * df_encoded[col].std()
    lower = df_encoded[col].mean() - 3 * df_encoded[col].std()
    df_encoded[col] = np.clip(df_encoded[col], lower, upper)

# Target Variable 3OS=1 where survival > 36

df_encoded["3OS"] = np.where(df_encoded["Overall Survival (months)"] > 36, 1, 0)
print("\n3OS distribution:\n", df_encoded["3OS"].value_counts())

# Visualizations
sns.heatmap(df_encoded.corr(numeric_only=True), cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.tight_layout()
plt.show()

fig = px.scatter(df_encoded, x="Overall Survival (months)", y="Fraction Genome Altered")
fig.show()

fig = px.scatter(
    df_encoded, x="Mutation Count", y="Overall Survival (months)",
    size="Tumor Grade", color="Age",
    hover_name="TMZ Treatment Cycles", log_x=True, size_max=60,
)
fig.show()

fig = px.scatter(
    df_encoded, x="ESTIMATE Score", y="Overall Survival (months)",
    size="Age", color="Tumor Grade",
    hover_name="TMZ Treatment Cycles", log_x=True, size_max=60,
)
fig.show()

fig = px.scatter_3d(
    df_encoded, x="Radiation Dose", y="Overall Survival (months)", z="Stromal Score",
    color="Tumor Grade", symbol="Cancer Type Detailed_Glioblastoma",
)
fig.show()

fig = px.histogram(df_encoded, x="Overall Survival (months)", nbins=20)
fig.show()

ID_COLS = ["Study ID", "Patient ID", "Sample ID", "Project ID", "Oncotree Code"]
df_encoded.drop(columns=[c for c in ID_COLS if c in df_encoded.columns], inplace=True)

TARGET_REG = "Overall Survival (months)"
TARGET_BIN = "3OS"

X_full = df_encoded.drop(columns=[TARGET_REG, "Overall Survival", TARGET_BIN])
y_reg  = df_encoded[TARGET_REG]
y_bin  = df_encoded[TARGET_BIN]

# Pearson Correlation FS with Linear Regression


def drop_correlated_features(X_tr, X_te, threshold=0.7):
    """Remove features correlated above threshold. Fit on train only."""
    corr_matrix = X_tr.corr()
    col_corr = set()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                col_corr.add(corr_matrix.columns[i])
    return X_tr.drop(col_corr, axis=1), X_te.drop(col_corr, axis=1), col_corr

X_train, X_test, y_train, y_test = train_test_split(
    X_full, y_reg, test_size=0.2, random_state=RANDOM_STATE
)

X_train_corr, X_test_corr, dropped = drop_correlated_features(X_train, X_test, threshold=0.7)
print(f"\nDropped {len(dropped)} correlated features: {dropped}")

sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train_corr)
X_test_sc  = sc.transform(X_test_corr)

lr = LinearRegression()
lr.fit(X_train_sc, y_train)
print(f"\nLinear Regression R²: {lr.score(X_test_sc, y_test):.4f}")

# PCA + LINEAR REGRESSION

log_y = np.log1p(y_reg)

X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(
    X_full, log_y, test_size=0.2, random_state=RANDOM_STATE
)

sc_p = StandardScaler()
X_train_p_sc = sc_p.fit_transform(X_train_p)
X_test_p_sc  = sc_p.transform(X_test_p)

n_components = min(40, X_train_p_sc.shape[1])
pca = PCA(n_components=n_components, random_state=RANDOM_STATE)
X_train_pca = pca.fit_transform(X_train_p_sc)
X_test_pca  = pca.transform(X_test_p_sc)

print(f"\nExplained variance (first 10 PCs): "
      f"{pca.explained_variance_ratio_[:10].cumsum()[-1]:.3f}")

lr_pca = LinearRegression()
lr_pca.fit(X_train_pca, y_train_p)

y_pred_pca = lr_pca.predict(X_test_pca)
print(f"PCA + Linear Regression R²: {r2_score(y_test_p, y_pred_pca):.4f}")

train_pred  = lr_pca.predict(X_train_pca)
train_resid = train_pred - y_train_p.to_numpy()
test_resid  = y_pred_pca - y_test_p.to_numpy()

plt.figure()
plt.scatter(train_pred, train_resid, color="red",  s=10, label="Train")
plt.scatter(y_pred_pca, test_resid,  color="pink", s=10, label="Test")
plt.axhline(0, linewidth=2, color="black")
plt.xlabel("Predicted")
plt.ylabel("Residual")
plt.title("Residual Plot — PCA + Linear Regression")
plt.legend()
plt.show()

# RFECV

X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_full, y_reg, test_size=0.2, random_state=RANDOM_STATE
)

rf_selector = RandomForestRegressor(n_estimators=30, random_state=RANDOM_STATE)
rfecv = RFECV(estimator=rf_selector, step=1, cv=5, scoring="r2")
rfecv.fit(X_train_r, y_train_r)

X_train_rfe = rfecv.transform(X_train_r)
X_test_rfe  = rfecv.transform(X_test_r)

print(f"\nOptimal number of features (RFECV): {rfecv.n_features_}")
print(f"Best features: {X_full.columns[rfecv.support_].tolist()}")


plt.figure()
plt.xlabel("Number of features selected")
plt.ylabel("Mean CV R²")
plt.plot(
    range(1, len(rfecv.cv_results_["mean_test_score"]) + 1),
    rfecv.cv_results_["mean_test_score"],
)
plt.title("RFECV — Cross-Validated R² by Number of Features")
plt.show()

rf_final = RandomForestRegressor(n_estimators=10, random_state=RANDOM_STATE)
grid_rfe = {"max_depth": [2, 5]}
cv_rfe = GridSearchCV(rf_final, param_grid=grid_rfe, cv=5, scoring="r2")
cv_rfe.fit(X_train_rfe, y_train_r)

print(f"Best params (RFECV + RF): {cv_rfe.best_params_}")
print(f"Best CV R²: {cv_rfe.best_score_:.4f}")
print(f"Test MAE: {mean_absolute_error(y_test_r, cv_rfe.predict(X_test_rfe)):.4f}")
print(f"Test mean survival: {y_test_r.mean():.2f} months")

# Random Forest with MI FS and GridSearchCV Hyperparameter Tuning
X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(
    X_full, y_reg, test_size=0.2, random_state=RANDOM_STATE
)

selector_mi = SelectKBest(mutual_info_regression, k=10)
X_train_mi  = selector_mi.fit_transform(X_train_m, y_train_m)
X_test_mi   = selector_mi.transform(X_test_m)

mask_mi       = selector_mi.get_support()
selected_cols = X_full.columns[mask_mi]
print(f"\nMutual Info selected features:\n{selected_cols.tolist()}")

sc_mi        = StandardScaler()
X_train_mi_sc = sc_mi.fit_transform(X_train_mi)
X_test_mi_sc  = sc_mi.transform(X_test_mi)

grid_rf = {
    "n_estimators": [200, 300, 400, 500],
    "max_features": ["sqrt", "log2"],
    "max_depth":    [4, 5, 6, 7, 8],
    "criterion":    ["absolute_error", "squared_error", "friedman_mse", "poisson"],
    "random_state": [RANDOM_STATE],
}

rf_mi = GridSearchCV(
    estimator=RandomForestRegressor(), param_grid=grid_rf, cv=5, scoring="r2"
)
rf_mi.fit(X_train_mi_sc, y_train_m)

print(f"Best params (MI + RF): {rf_mi.best_params_}")
print(f"Best CV R²: {rf_mi.best_score_:.4f}")

# Gradient Boost Regr. With MI FS and GridSearchCV for Hyperparameter Tuning

X_train_g, X_test_g, y_train_g, y_test_g = train_test_split(
    X_full, y_reg, test_size=0.2, random_state=RANDOM_STATE
)

selector_gb = SelectKBest(mutual_info_regression, k=10)
X_train_gb  = selector_gb.fit_transform(X_train_g, y_train_g)
X_test_gb   = selector_gb.transform(X_test_g)

# Baseline GBR
gbr_base = GradientBoostingRegressor(random_state=RANDOM_STATE)
gbr_base.fit(X_train_gb, y_train_g)
print(f"\nBaseline GBR R²: {gbr_base.score(X_test_gb, y_test_g):.4f}")

grid_gb = {
    "n_estimators": [200, 300, 400, 500],
    "max_features": ["sqrt", "log2"],
    "max_depth":    [4, 5, 6, 7, 8],
    "criterion":    ["friedman_mse", "squared_error"],
    "random_state": [RANDOM_STATE],
}

gbr_cv = GridSearchCV(
    estimator=GradientBoostingRegressor(), param_grid=grid_gb, cv=5, scoring="r2"
)
gbr_cv.fit(X_train_gb, y_train_g)

print(f"Best params (GBR): {gbr_cv.best_params_}")
print(f"Best CV R²: {gbr_cv.best_score_:.4f}")

#Classification

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, ConfusionMatrixDisplay

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_full, y_bin, test_size=0.2, random_state=RANDOM_STATE, stratify=y_bin
)

selector_c  = SelectKBest(mutual_info_regression, k=10)
X_train_c_s = selector_c.fit_transform(X_train_c, y_train_c)
X_test_c_s  = selector_c.transform(X_test_c)

sc_c         = StandardScaler()
X_train_c_sc = sc_c.fit_transform(X_train_c_s)
X_test_c_sc  = sc_c.transform(X_test_c_s)

rfc = RandomForestClassifier(n_estimators=100, random_state=RANDOM_STATE)
rfc.fit(X_train_c_sc, y_train_c)

print("\n=== 3-Year Survival Classification (Random Forest) ===")
print(classification_report(y_test_c, rfc.predict(X_test_c_sc),
                             target_names=["≤36 months", ">36 months"]))

ConfusionMatrixDisplay.from_estimator(
    rfc, X_test_c_sc, y_test_c,
    display_labels=["≤36 months", ">36 months"],
)
plt.title("3OS Classification — Confusion Matrix")
plt.show()

print("\nAnalysis complete.")